// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt2kIsb_cIqIevUdyxMSfZbRzZjlKqcac',
    appId: '1:533417546665:web:2ed5c299c805227edbeab8',
    messagingSenderId: '533417546665',
    projectId: 'volsapp-e2538',
    authDomain: 'volsapp-e2538.firebaseapp.com',
    storageBucket: 'volsapp-e2538.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVucQBuqlnWvZqX8iMQv27d8ijoMgMS68',
    appId: '1:533417546665:android:89c6245bae1c0168dbeab8',
    messagingSenderId: '533417546665',
    projectId: 'volsapp-e2538',
    storageBucket: 'volsapp-e2538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsD4ykvAywopMt81RxMKPqi-LidjrCq24',
    appId: '1:533417546665:ios:d3ba3b3edc6e2267dbeab8',
    messagingSenderId: '533417546665',
    projectId: 'volsapp-e2538',
    storageBucket: 'volsapp-e2538.appspot.com',
    iosBundleId: 'com.example.volsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsD4ykvAywopMt81RxMKPqi-LidjrCq24',
    appId: '1:533417546665:ios:72dd848d80d1ff2adbeab8',
    messagingSenderId: '533417546665',
    projectId: 'volsapp-e2538',
    storageBucket: 'volsapp-e2538.appspot.com',
    iosBundleId: 'com.example.volsApp.RunnerTests',
  );
}
